version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: covid_db
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
